@Dynamic_Health_Check_Demo_HostAddress = http://localhost:5183

###
 
GET {{Dynamic_Health_Check_Demo_HostAddress}}/health
Accept: application/json

###
 
GET {{Dynamic_Health_Check_Demo_HostAddress}}/log/logWarning
Accept: application/json

###

GET {{Dynamic_Health_Check_Demo_HostAddress}}/log/logError
Accept: application/json

###

GET {{Dynamic_Health_Check_Demo_HostAddress}}/log/logCritical
Accept: application/json
